version: '3'

services:
  app:
    container_name: air-tickets
    image: air-tickets
    build: .
    ports:
      - '3000:3000'
      - '8080:8080'
    volumes:
      - ./src:/app/src
      - ./DB:/app/DB
